name: Update Feed
on:
 - push
##- schedule:
##  - cron: "0 */1 * * *"
jobs:
  update-feed:
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v4
      - name: install deps
        run: corepack yarn install
      - name: Run the script
        run: corepack yarn build
      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh }}
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updating TODO.txt"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master

